---
language: node_js
node_js:
  - "6.1.x"
env:
  - CXX=g++-4.8
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
notifications:
   email: false
git:
  depth: 10
